In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
myarray = np.array(mylist)

In [6]:
type(myarray)

numpy.ndarray

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [16]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.random.seed(101)
arr = np.random.randint(0,100,5)

In [18]:
arr

array([95, 11, 81, 70, 63])

In [25]:
arr2 = np.random.randint(0,100,10)
arr2

array([34, 44, 72, 19, 10, 76, 95, 87,  0, 73])

In [20]:
arr.max()
arr.argmax()

0

In [21]:
arr.min()

11

In [22]:
arr.argmin()

1

In [23]:
arr.mean()

64.0

In [27]:
arr2.reshape(5,2)

array([[34, 44],
       [72, 19],
       [10, 76],
       [95, 87],
       [ 0, 73]])

In [46]:
arr3 = np.arange(0,100).reshape(10,10)
arr3
arr4 = arr3.copy()

In [47]:
arr3[4,6]

46

In [48]:
arr3[:,4]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [49]:
arr4

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])